# Generated by Django 5.2.12 on 2026-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completion_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='extension_prompt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
